spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret-key: aGVsbG8td29ybGQtdGhpcy1pcy1hLXNlY3JldC1rZXkK
    expiration-time: 86400000
